<?php
session_name('paing_chan'); // name the session to prevent conflicts with other applications
session_start();
include_once 'head.php'; ?>

<body>
    <?php include_once 'header.php'; ?>

    <main id="main-mt">
        <div class="container mt-4">
            <h1 class="mb-4">About This Web Application</h1>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Section</th>
                        <th scope="col">Details</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Tasks Completed -->
                    <tr>
                        <td><strong>Tasks Completed</strong></td>
                        <td>
                            <ul>
                                <li>Part 1: Database Table Creation for the Plant Biodiversity project</li>
                                <li>Part 2: Register and Login Functions</li>
                                <li>Part 3: User Interaction Pages of the Alumni Portal </li>
                                <li>Part 4: Admin Interaction Pages of the the project </li>
                                <li>Part 5: Extension tasks</li>
                            </ul>
                        </td>
                    </tr>

                    <!-- Tasks Not Attempted or Not Completed -->
                    <tr>
                        <td><strong>Tasks Not Completed</strong></td>
                        <td>None. All tasks have been completed.</td>
                    </tr>

                    <!-- Part trouble with -->
                    <tr>
                        <td><strong>Part I Had Trouble With</strong></td>
                        <td>
                            <p>Training AI model to detect plants correctly using Teachable Machine</p>
                            <p>Generating PDF reports accurately with DOMPDF</p>
                            <p>Setting up MySQL queries to handle plant data efficiently</p>
                            <p>Integrating the trained model with the PHP backend</p>
                        </td>
                    </tr>

                    <!-- Part I would like to do better next time -->
                    <tr>
                        <td><strong>Part I Would Like to Do Better Next Time</strong></td>
                        <td>
                            <p>Optimize AI model training for higher accuracy</p>
                            <p>Enhance the styling of PDF reports generated by DOMPDF</p>
                            <p>Write more efficient and secure SQL queries</p>
                            <p>Improve the integration process of AI models with PHP</p>
                        </td>
                    </tr>

                    <!-- Extra challenges that I have done -->
                    <tr>
                        <td><strong>Extra Challenges</strong></td>
                        <td>
                            <p>Train the AI model using custom plant images in Teachable Machine</p>
                            <p>Implement reset password functionality</p>
                            <p>Generate PDF files dynamically with plant details using DOMPDF</p>
                            <p>Develop a "Download PDF" feature for detailed plant descriptions</p>
                            <p>Integrate Teachable Machine's model with PHP for real-time plant identification</p>
                        </td>
                    </tr>


                    <!-- Video Presentation -->
                    <tr>
                        <td><strong>Video Presentation</strong></td>
                        <td>
                            <a href="https://youtu.be/elcuYqedw8U" target="_blank" class="btn btn-primary">Link to Youtube</a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <!-- Return to Home -->
            <div class="text-center">
                <a href="index.php" class="btn btn-success">Back to Home Page</a>
            </div>
        </div>
    </main>
    <?php include_once 'back-to-top.php' ?>
    <?php include_once 'footer.php' ?>
</body>

</html>